# Generated by Django 4.2.8 on 2026-03-12 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.office')),
            ],
        ),
    ]
